// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-variants/ActionFirst.tsx": () => import("../components/mockups/dashboard-variants/ActionFirst.tsx"),
  "./components/mockups/dashboard-variants/ActionFirstFocused.tsx": () => import("../components/mockups/dashboard-variants/ActionFirstFocused.tsx"),
  "./components/mockups/dashboard-variants/ActionFirstStreamlined.tsx": () => import("../components/mockups/dashboard-variants/ActionFirstStreamlined.tsx"),
  "./components/mockups/dashboard-variants/CommandCenter.tsx": () => import("../components/mockups/dashboard-variants/CommandCenter.tsx"),
  "./components/mockups/dashboard-variants/DailyBriefing.tsx": () => import("../components/mockups/dashboard-variants/DailyBriefing.tsx"),
  "./components/mockups/dashboard-variants/DailyBriefingEditorial.tsx": () => import("../components/mockups/dashboard-variants/DailyBriefingEditorial.tsx"),
  "./components/mockups/dashboard-variants/DailyBriefingPolished.tsx": () => import("../components/mockups/dashboard-variants/DailyBriefingPolished.tsx"),
  "./components/mockups/dashboard-variants/PipelineFunnel.tsx": () => import("../components/mockups/dashboard-variants/PipelineFunnel.tsx"),
  "./components/mockups/dashboard-variants/SaaSMainDashboard.tsx": () => import("../components/mockups/dashboard-variants/SaaSMainDashboard.tsx"),
  "./components/mockups/contacts-variants/CommandFirst.tsx": () => import("../components/mockups/contacts-variants/CommandFirst.tsx"),
  "./components/mockups/contacts-variants/IntelligenceHub.tsx": () => import("../components/mockups/contacts-variants/IntelligenceHub.tsx"),
  "./components/mockups/contacts-variants/PowerDataTable.tsx": () => import("../components/mockups/contacts-variants/PowerDataTable.tsx"),
  "./components/mockups/contacts-variants/TwoPanelWorkspace.tsx": () => import("../components/mockups/contacts-variants/TwoPanelWorkspace.tsx"),
  "./components/mockups/landing-variants/Authority.tsx": () => import("../components/mockups/landing-variants/Authority.tsx"),
  "./components/mockups/landing-variants/Signal.tsx": () => import("../components/mockups/landing-variants/Signal.tsx")
};
